---
# tasks file for dockerize
- name: Copy python tar image to remote host
  copy:
    src: "{{ path_to_image }}"
    dest: ./
- name: Loading python tar image to image
  shell: "docker load --input {{ path_to_image.split('/')[4] }}"
- name: Run container to check dockerize
  docker_container:
    image: "{{ path_to_image.split('/')[4].split('.')[0] }}:{{ version }}"
    name: "{{ path_to_image.split('/')[4].split('.')[0] }}"
    recreate: yes
    state: started
  register: result
  retries: 5
  until: result is succeeded
- name: Check running of module in remote container
  shell: "docker logs {{ path_to_image.split('/')[4].split('.')[0] }} "
  register: result
- name: fail the play if the previous command did not succeed
  fail:
    msg: "The running module in remote host is failed"
  when: " '{{ string_to_check }}' not in result.stdout"


