---
- hosts: all
  remote_user: ubuntu
  become: yes
  name: Install requirements to run playbook properly and run python module
  gather_facts: false
  pre_tasks:
   - raw: timedatectl  set-timezone Asia/Jerusalem && apt update && apt install -y ntpdate && ntpdate ntp.ubuntu.com && apt update && apt install -y python-pip && pip install docker
  roles:
         - { role: dockerize}